### ISSUE TITLE
Version 0.2.0 Roadmap

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship-barge#1]
- [x] Use Argon2i as a KDF
  - [x] Use SENSITIVE for master keys.
  - [x] Use MODERATE for signing keys.
- [x] Cabins
  - [x] Create skeleton
  - [x] Integrate with Git (for later integration with [Pharaoh](https://github.com/paragonie/pharaoh)
  - [x] Build and sign .phar
  - [x] Submit to Channel
- [x] Gadgets
  - [x] Create skeleton
  - [x] Integrate with Git
  - [x] Build and sign .phar
  - [x] Submit to Channel
- [x] Motifs
  - [x] Create skeleton
  - [x] Integrate with Git
  - [x] Build and sign .zip
  - [x] Submit to Channel
